version: "3"
services:
  mongo:
    container_name: "mongodb"
    hostname: "mongodb"
    image: "mongo:latest"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: customers
      MONGO_INITDB_USERNAME: customers
      MONGO_INITDB_PASSWORD: customers