FROM maven:3.6.3-openjdk-15-slim AS build
COPY . .
RUN mvn clean package

FROM openjdk:15-jdk-alpine
RUN mkdir app
COPY --from=build /target/*.jar /app/realtime-reload.jar 
WORKDIR /app
ENTRYPOINT java -jar realtime-reload.jar